export const ADD_ITEM = 'ADD_ITEM';
export const SET_FILTER = 'SET_FILTER';
export const SET_ALL_CHECKED = 'SET_ALL_CHECKED';
export const CHANGE_COMPLETED = 'CHANGE_COMPLETED';
export const CHANGE_EDITING = 'CHANGE_EDITING';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CONFIRM_MODAL = 'CONFIRM_MODAL';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const GET_ITEMS_FOR_USER = 'GET_ITEMS_FOR_USER';
export const LOGOUT = 'LOGOUT';
export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_ERR = 'REGISTRATION_ERR';
export const SUBMIT_FORM_ERR = 'SUBMIT_FORM_ERR';
export const SET_ALL_ITEMS_CHECKED = 'SET_ALL_ITEMS_CHECKED';
export const REMOVE_ITEMS_ON_CONFIRM_MODAL = 'REMOVE_ITEMS_ON_CONFIRM_MODAL';

export const Filters = {
    ALL: 'ALL',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED'
}