export const SET_FILTER = 'SET_FILTER';
export const SET_ALL_CHECKED = 'SET_ALL_CHECKED';
export const CHANGE_EDITING = 'CHANGE_EDITING';
// export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CONFIRM_MODAL = 'CONFIRM_MODAL';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const LOGOUT = 'LOGOUT';
export const SET_LIST_OF_USERS = 'SET_LIST_OF_USERS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const ADD_ITEM = {
    REQUEST: 'ADD_ITEM_REQUEST',
    SUCCESS: 'ADD_ITEM_SUCCESS',
    ERROR: 'ADD_ITEM_ERROR'
}
export const SUBMIT_FORM = {
    REQUEST: 'SUBMIT_FORM_REQUEST',
    SUCCESS: 'SUBMIT_FORM_SUCCESS',
    ERROR: 'SUBMIT_FORM_ERROR'
}
export const REGISTRATION = {
    REQUEST: 'REGISTRATION_REQUEST',
    SUCCESS: 'REGISTRATION_SUCCESS',
    ERROR: 'REGISTRATION_ERROR'
}
export const GET_ITEMS_FOR_USER = {
    REQUEST: 'GET_ITEMS_FOR_USER_REQUEST',
    SUCCESS: 'GET_ITEMS_FOR_USER_SUCCESS',
    ERROR: 'GET_ITEMS_FOR_USER_ERROR'
}
export const SET_ALL_ITEMS_CHECKED = {
    REQUEST: 'SET_ALL_ITEMS_CHECKED_REQUEST',
    SUCCESS: 'SET_ALL_ITEMS_CHECKED_SUCCESS',
    ERROR: 'SET_ALL_ITEMS_CHECKED_ERROR'
}
export const REMOVE_ITEMS_ON_CONFIRM_MODAL = {
    REQUEST: 'REMOVE_ITEMS_ON_CONFIRM_MODAL_REQUEST',
    SUCCESS: 'REMOVE_ITEMS_ON_CONFIRM_MODAL_SUCCESS',
    ERROR: 'REMOVE_ITEMS_ON_CONFIRM_MODAL_ERROR'
}
export const CHANGE_COMPLETED = {
    REQUEST: 'CHANGE_COMPLETED_REQUEST',
    SUCCESS: 'CHANGE_COMPLETED_SUCCESS',
    ERROR: 'CHANGE_COMPLETED_ERROR'
}
export const UPDATE_ITEM = {
    REQUEST: 'UPDATE_ITEM_REQUEST',
    SUCCESS: 'UPDATE_ITEM_SUCCESS',
    ERROR: 'UPDATE_ITEM_ERROR'
}

export const Filters = {
    ALL: 'ALL',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED'
}